/**
 * ROOM-CONFIG.JS (v2.0)
 * =====================
 * Shared room configuration module for Cherry Tree Centre
 * 
 * FULLY DYNAMIC — no hardcoded room names, IDs, or mappings.
 * Everything is driven by room_config in Firebase.
 * 
 * The Firebase key IS the roomID (e.g. "H1", "H6", "HCP", "BH1").
 * displayName is for humans only (e.g. "Room 1", "Car Park").
 * Multiple rooms can share the same displayName across locations.
 * 
 * Usage: Include after Firebase init, call loadRoomConfig() before loading bookings
 * <script src="room-config.js"></script>
 */

(function() {
  'use strict';
  console.log('🏠 room-config.js v2.0 loading...');

  // ================================
  // STATE (exposed globally)
  // ================================
  window.roomConfig = {};       // Full config keyed by roomID
  window.enabledRooms = [];     // Sorted array of enabled rooms [{key, displayName, ...}]

  // Internal lookup indexes — built on load for fast resolution
  let _displayNameIndex = {};   // displayName → [roomID, roomID, ...] (may have duplicates)
  let _locationRoomIndex = {};  // location → [roomID, roomID, ...]

  // ================================
  // LOAD ROOM CONFIG FROM FIREBASE
  // ================================
  window.loadRoomConfig = async function() {
    console.log('🏠 Loading room configuration from Firebase...');
    
    try {
      if (typeof database === 'undefined') {
        console.error('❌ Firebase database not available — cannot load room config');
        window.roomConfig = {};
        window.enabledRooms = [];
        return window.roomConfig;
      }

      const snapshot = await database.ref('room_config').once('value');
      const config = snapshot.val();
      
      if (config && Object.keys(config).length > 0) {
        window.roomConfig = config;
        console.log('✅ Loaded room config from Firebase:', Object.keys(config).length, 'rooms');
      } else {
        console.warn('⚠️ No room config found in Firebase — calendar will be empty');
        window.roomConfig = {};
      }
      
      // Build enabled rooms array sorted by order
      _buildEnabledRooms();
      
      // Build lookup indexes
      _buildIndexes();
      
      // Generate dynamic CSS for room colours
      _generateRoomStyles();
      
      return window.roomConfig;
      
    } catch (error) {
      console.error('❌ Error loading room config:', error);
      window.roomConfig = {};
      window.enabledRooms = [];
      return window.roomConfig;
    }
  };

  // ================================
  // BUILD ENABLED ROOMS ARRAY
  // ================================
  function _buildEnabledRooms() {
    window.enabledRooms = Object.entries(window.roomConfig)
      .filter(([key, room]) => room.enabled)
      .sort((a, b) => {
        // Primary sort: location (group rooms by location)
        const locA = a[1].location || '';
        const locB = b[1].location || '';
        if (locA !== locB) return locA.localeCompare(locB);
        // Secondary sort: order within location
        return (a[1].order || 99) - (b[1].order || 99);
      })
      .map(([key, room]) => ({ key, ...room }));
    
    console.log(`🏠 ${window.enabledRooms.length} enabled rooms loaded`);
  }

  // ================================
  // BUILD LOOKUP INDEXES
  // ================================
  function _buildIndexes() {
    _displayNameIndex = {};
    _locationRoomIndex = {};
    
    Object.entries(window.roomConfig).forEach(([roomID, room]) => {
      // Index by displayName (lowercased for case-insensitive lookup)
      const nameKey = (room.displayName || '').toLowerCase().trim();
      if (nameKey) {
        if (!_displayNameIndex[nameKey]) _displayNameIndex[nameKey] = [];
        _displayNameIndex[nameKey].push(roomID);
      }
      
      // Also index by displayName with underscores (handles "Room_1" → "room 1")
      const underscoreKey = nameKey.replace(/_/g, ' ');
      if (underscoreKey !== nameKey) {
        if (!_displayNameIndex[underscoreKey]) _displayNameIndex[underscoreKey] = [];
        _displayNameIndex[underscoreKey].push(roomID);
      }
      
      // Index by location
      const loc = room.location || 'unknown';
      if (!_locationRoomIndex[loc]) _locationRoomIndex[loc] = [];
      _locationRoomIndex[loc].push(roomID);
    });
    
    console.log('🔍 Lookup indexes built:',
      Object.keys(_displayNameIndex).length, 'display names,',
      Object.keys(_locationRoomIndex).length, 'locations');
  }

  // ================================
  // GENERATE DYNAMIC CSS
  // ================================
  function _generateRoomStyles() {
    let styleEl = document.getElementById('room-dynamic-styles');
    if (!styleEl) {
      styleEl = document.createElement('style');
      styleEl.id = 'room-dynamic-styles';
      document.head.appendChild(styleEl);
    }
    
    let css = '/* Dynamic room colours — generated by room-config.js v2.0 */\n';
    
    window.enabledRooms.forEach(room => {
      const className = _cssClass(room.key);
      
      // Grid cell styles for booked cells (day view)
      css += `.grid-cell.booked.${className} { background: ${room.color}; border-left: 4px solid ${room.borderColor}; }\n`;
      
      // Booking segment styles (for multi-booking cells in week view)
      css += `.booking-segment.${className} { background: ${room.color}; border-left: 3px solid ${room.borderColor}; }\n`;
      
      // Legend colour styles
      css += `.legend-color.${className} { background: ${room.color}; border-color: ${room.borderColor}; }\n`;
      
      // Car park type gets slightly transparent
      if (room.type === 'car_park') {
        css += `.grid-cell.booked.${className} { opacity: 0.85; }\n`;
        css += `.booking-segment.${className} { opacity: 0.85; }\n`;
      }
    });
    
    styleEl.textContent = css;
    console.log('🎨 Dynamic room styles generated');
  }

  // ================================
  // CSS CLASS HELPER
  // ================================
  function _cssClass(roomKey) {
    // Convert roomID to a safe CSS class name
    // "H6" → "room-h6", "HCP" → "room-hcp", "BH1" → "room-bh1"
    return 'room-' + roomKey.toLowerCase().replace(/[^a-z0-9]/g, '-');
  }

  // ================================
  // ROOM LOOKUP FUNCTIONS
  // ================================

  /**
   * Get roomID from a booking record.
   * 
   * Resolution order:
   * 1. Direct match: booking.room matches a key in roomConfig (new format)
   * 2. Display name match: booking.room matches a displayName
   *    - If unique, returns that roomID
   *    - If ambiguous (e.g. three "Room 1"s), uses booking.locationId/location to disambiguate
   * 3. Normalised match: tries underscores→spaces, case-insensitive
   * 4. Online detection: checks booking.location for "online"
   * 5. Returns null if no match (logs warning)
   * 
   * NO HARDCODED ROOM NAMES — everything comes from the loaded config.
   */
  window.getRoomKey = function(booking) {
    if (!booking) return null;
    
    const room = booking.room;
    
    // 1. Direct key match (new format: "H6", "HCP", etc.)
    if (room && window.roomConfig[room]) {
      return room;
    }
    
    // 2. Online detection via location field
    if (booking.location && booking.location.toLowerCase().includes('online')) {
      const onlineRoom = _findByType('online');
      if (onlineRoom) return onlineRoom;
    }
    
    if (!room) return null;
    
    // 3. Display name match (handles "Room 6", "Car Park", etc.)
    const normalised = room.toLowerCase().replace(/_/g, ' ').trim();
    const candidates = _displayNameIndex[normalised];
    
    if (candidates && candidates.length === 1) {
      // Unambiguous match
      return candidates[0];
    }
    
    if (candidates && candidates.length > 1) {
      // Ambiguous — multiple rooms with same display name (e.g. "Room 1" at 3 locations)
      // Use booking's location to disambiguate
      const resolved = _disambiguateByLocation(candidates, booking);
      if (resolved) return resolved;
      
      // Can't disambiguate — log warning and return first match
      console.warn(`⚠️ Ambiguous room "${room}" — ${candidates.length} matches, using first:`, candidates[0]);
      return candidates[0];
    }
    
    // 4. Try matching just the room value as-is (handles edge cases)
    // e.g. if someone stored just "6", try matching against displayName containing "6"
    for (const [roomID, config] of Object.entries(window.roomConfig)) {
      const dn = (config.displayName || '').toLowerCase();
      // Match "6" to "Room 6", "1" to "Room 1", etc.
      if (dn === `room ${normalised}` || dn === normalised) {
        return roomID;
      }
    }
    
    // 5. No match
    console.warn(`⚠️ Could not resolve room "${room}" to any roomID in config`);
    return null;
  };

  /**
   * Disambiguate multiple roomID candidates using the booking's location info.
   */
  function _disambiguateByLocation(candidates, booking) {
    // Try locationId first (more reliable)
    if (booking.locationId) {
      for (const roomID of candidates) {
        const cfg = window.roomConfig[roomID];
        // Check if location config has a matching locationId
        // locationId "2" = henley, "1" = buckhurst_hill (from pricing_config convention)
        if (cfg && cfg.locationId === booking.locationId) return roomID;
      }
    }
    
    // Try location name
    if (booking.location) {
      const bookingLoc = booking.location.toLowerCase().trim();
      for (const roomID of candidates) {
        const cfg = window.roomConfig[roomID];
        if (!cfg) continue;
        const roomLoc = (cfg.location || '').toLowerCase().replace(/_/g, ' ');
        if (roomLoc === bookingLoc || bookingLoc.includes(roomLoc) || roomLoc.includes(bookingLoc)) {
          return roomID;
        }
      }
    }
    
    return null;
  }

  /**
   * Find first roomID with a given type.
   */
  function _findByType(type) {
    for (const [roomID, config] of Object.entries(window.roomConfig)) {
      if (config.type === type && config.enabled) return roomID;
    }
    return null;
  }

  /**
   * Get room mapping for cell IDs and CSS classes.
   * 
   * Returns { roomNumber, roomClass } where:
   *   roomNumber = the roomID (used in cell IDs like "cell-H6-09:00")
   *   roomClass  = CSS-safe class (used for colour styling)
   * 
   * NO HARDCODED MAPPINGS — derived directly from the roomID.
   */
  window.getRoomMapping = function(booking) {
    const roomKey = window.getRoomKey(booking);
    
    if (!roomKey) {
      return { roomNumber: null, roomClass: '' };
    }
    
    return {
      roomNumber: roomKey,              // "H6" — used for cell IDs
      roomClass: _cssClass(roomKey)     // "room-h6" — used for CSS
    };
  };

  /**
   * Get the cell ID prefix for a room key.
   * Used when building grid cells and looking up cells for bookings.
   * 
   * Returns the roomKey directly — cell IDs are "cell-{roomKey}-{time}"
   */
  window.getRoomCellId = function(roomKey) {
    return roomKey;
  };

  /**
   * Get display name for a room from a booking or roomID.
   * 
   * Can accept either:
   *   - A booking object (resolves via getRoomKey)
   *   - A roomID string (direct lookup)
   */
  window.getRoomDisplayName = function(bookingOrKey) {
    let roomKey;
    
    if (typeof bookingOrKey === 'string') {
      roomKey = bookingOrKey;
    } else {
      roomKey = window.getRoomKey(bookingOrKey);
    }
    
    if (!roomKey) {
      // Return raw room value if available
      if (bookingOrKey && typeof bookingOrKey === 'object') {
        return bookingOrKey.room || 'Unknown';
      }
      return 'Unknown';
    }
    
    if (window.roomConfig[roomKey] && window.roomConfig[roomKey].displayName) {
      return window.roomConfig[roomKey].displayName;
    }
    
    // Fallback: return the key itself
    return roomKey;
  };

  /**
   * Get room colour from config.
   */
  window.getRoomColor = function(roomKey) {
    if (window.roomConfig[roomKey]) {
      return {
        color: window.roomConfig[roomKey].color || '#e0e0e0',
        borderColor: window.roomConfig[roomKey].borderColor || '#ccc'
      };
    }
    return { color: '#e0e0e0', borderColor: '#ccc' };
  };

  /**
   * Get the type of a room ("therapy_room", "car_park", "online").
   */
  window.getRoomType = function(roomKey) {
    if (window.roomConfig[roomKey]) {
      return window.roomConfig[roomKey].type || 'therapy_room';
    }
    return null;
  };

  /**
   * Check if a room is a car park (by type, not by name).
   * Accepts a roomID string.
   */
  window.isCarPark = function(roomKey) {
    return window.getRoomType(roomKey) === 'car_park';
  };

  /**
   * Check if a room is an online room (by type, not by name).
   * Accepts a roomID string.
   */
  window.isOnline = function(roomKey) {
    return window.getRoomType(roomKey) === 'online';
  };

  /**
   * Get all enabled rooms for a specific location.
   * Returns array of {key, displayName, ...} sorted by order.
   * 
   * @param {string} locationKey - e.g. "henley", "buckhurst_hill"
   */
  window.getRoomsForLocation = function(locationKey) {
    return window.enabledRooms.filter(r => r.location === locationKey);
  };

  /**
   * Get all enabled rooms of a specific type.
   * Returns array of {key, displayName, ...} sorted by order.
   * 
   * @param {string} type - e.g. "therapy_room", "car_park", "online"
   */
  window.getRoomsByType = function(type) {
    return window.enabledRooms.filter(r => r.type === type);
  };

  /**
   * Get the locationId for a room (from room config, not hardcoded).
   * Used for pricing lookups.
   * 
   * @param {string} roomKey - the roomID
   * @returns {string|null} locationId (e.g. "1", "2")
   */
  window.getLocationIdForRoom = function(roomKey) {
    const cfg = window.roomConfig[roomKey];
    if (!cfg) return null;
    return cfg.locationId || null;
  };

  /**
   * Get the location key (e.g. "henley") for a room.
   */
  window.getLocationKeyForRoom = function(roomKey) {
    const cfg = window.roomConfig[roomKey];
    if (!cfg) return null;
    return cfg.location || null;
  };

  /**
   * Get the capacity for a room (defaults to 1).
   * Car parks typically have higher capacity.
   */
  window.getRoomCapacity = function(roomKey) {
    const cfg = window.roomConfig[roomKey];
    if (!cfg) return 1;
    return cfg.capacity || 1;
  };

  /**
   * Get the legacy SBM henleyRoomId for a room (used in Make.com scenarios).
   * Returns null if not set.
   */
  window.getHenleyRoomId = function(roomKey) {
    const cfg = window.roomConfig[roomKey];
    if (!cfg) return null;
    return cfg.henleyRoomId || null;
  };

  /**
   * Get the legacy SBM serviceId for a room.
   * Returns null if not set.
   */
  window.getServiceIdForRoom = function(roomKey) {
    const cfg = window.roomConfig[roomKey];
    if (!cfg) return null;
    return cfg.serviceId || null;
  };

  /**
   * Get all unique locations that have enabled rooms.
   * Returns array of {key, name, rooms} objects.
   */
  window.getActiveLocations = function() {
    const locations = {};
    
    window.enabledRooms.forEach(room => {
      const loc = room.location || 'unknown';
      if (!locations[loc]) {
        locations[loc] = { key: loc, name: _locationDisplayName(loc), rooms: [] };
      }
      locations[loc].rooms.push(room);
    });
    
    return Object.values(locations);
  };

  /**
   * Convert a location key to a display name.
   */
  function _locationDisplayName(locationKey) {
    const names = {
      'henley': 'Henley',
      'buckhurst_hill': 'Buckhurst Hill',
      'online': 'Online'
    };
    return names[locationKey] || locationKey.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  }

  /**
   * Utility: Get the CSS class for a roomID.
   * Exposed globally for use by other files.
   */
  window.getRoomCssClass = function(roomKey) {
    return _cssClass(roomKey);
  };

  console.log('✅ room-config.js v2.0 loaded — call loadRoomConfig() after Firebase init');
})();
